version: "3.9"
services:

  mariadb:
    image: mariadb
    environment:
      - MARIADB_DATABASE=republichat
      - MARIADB_ROOT_PASSWORD=fractal
    volumes:
      - ./Server/Database/structure.sql:/docker-entrypoint-initdb.d/structure.sql
      - ./docker-configs/my.cnf:/etc/mysql/my.cnf
    ports:
      - "3306:3306"
    restart: unless-stopped

  client:
    build: .
    ports:
      - "8080:80"
    restart: unless-stopped

  server:
    build: ./Server
    volumes:
      - /containers/nginx-proxy-manager/letsencrypt/live/npm-2/cert.pem:/republi-chat/Server/Certifications/cert.pem
      - /containers/nginx-proxy-manager/letsencrypt/live/npm-2/privkey.pem:/republi-chat/Server/Certifications/privkey.pem
    ports:
      - "9696:9696"
    depends_on:
      - mariadb
    restart: unless-stopped
